name: models
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.11